# Generated by Django 5.0.6 on 2024-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
