# Generated by Django 5.0.6 on 2024-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_lessons', '0005_remove_likedislike_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='like_dislike',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('NULL', 'NULL')], default='NULL', max_length=15),
        ),
    ]
